- name: "Add wheezy-backport to sources.list"
  apt_repository: >
    state=present
    repo="deb http://http.debian.net/debian wheezy-backports main"
  when: ansible_distribution_major_version|int == 7
  tags:
    - zeromq
    - repos

- name: "Ensure zmq is installed"
  apt: >
    name={{ item }}
    state=present
  with_items:
    - libzmq3
    - libzmq3-dev
  tags:
    - zeromq
    - pkgs
